import { useMemo, useState } from 'react';
import { ArrowLeft, Printer, Search } from 'lucide-react';
import DataTable from './DataTable';

function escapeHtml(value) { return String(value || '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character])); }

export default function StudentListModule({ rows, loading, error, t, onBack }) {
    const [query, setQuery] = useState(''); const [className, setClassName] = useState('all');
    const classes = [...new Set(rows.map((student) => student.className).filter(Boolean))].sort();
    const visible = useMemo(() => rows.filter((student) => (className === 'all' || student.className === className) && [student.fullName, student.admissionNumber, student.className, student.parentEmail].some((value) => String(value || '').toLowerCase().includes(query.toLowerCase()))), [rows, className, query]);
    const printStudents = () => { const popup = window.open('', '_blank', 'width=1000,height=700'); if (!popup) return; popup.document.write(`<html><head><title>FKAMS Students</title><style>body{font-family:Arial;padding:24px}h1{color:#17333d}table{border-collapse:collapse;width:100%;margin-top:20px}th,td{border:1px solid #cbd5e1;padding:9px;text-align:left;font-size:12px}th{background:#e2e8f0}</style></head><body><h1>Forever King Academy - Students</h1><p>Class: ${className === 'all' ? 'All classes' : className}</p><table><thead><tr><th>Admission number</th><th>Full name</th><th>Class</th><th>Parent email</th><th>Status</th></tr></thead><tbody>${visible.map((student) => `<tr><td>${escapeHtml(student.admissionNumber)}</td><td>${escapeHtml(student.fullName)}</td><td>${escapeHtml(student.className)}</td><td>${escapeHtml(student.parentEmail)}</td><td>${escapeHtml(student.status)}</td></tr>`).join('')}</tbody></table></body></html>`); popup.document.close(); popup.focus(); popup.print(); };
    return <div className="space-y-6"><button onClick={onBack} className="flex items-center gap-2 text-xs font-bold text-cyan-700"><ArrowLeft size={16} />{t.overview}</button><section className="rounded-3xl bg-[#17333d] p-6 text-white shadow-xl sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-teal-200">Students</p><h1 className="mt-2 font-display text-2xl font-bold">Student directory</h1><p className="mt-2 text-sm text-slate-300">Search students, filter by class, and print the current list.</p></div><button onClick={printStudents} className="flex items-center justify-center gap-2 rounded-xl bg-teal-300 px-4 py-3 text-xs font-bold text-[#17333d]"><Printer size={16} /> Print {className === 'all' ? 'all' : className}</button></div></section><section className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by name, admission number or email" className="w-full rounded-xl border border-slate-200 py-3 pl-10 pr-3 text-xs outline-none focus:border-cyan-600" /></label><select value={className} onChange={(event) => setClassName(event.target.value)} className="rounded-xl border border-slate-200 px-3 py-3 text-xs"><option value="all">All classes ({rows.length})</option>{classes.map((name) => <option key={name} value={name}>{name}</option>)}</select></section>{error && <div className="rounded-xl bg-amber-50 px-4 py-3 text-xs text-amber-800">{error}</div>}{loading ? <div className="rounded-2xl bg-white p-14 text-center text-xs text-slate-400">{t.loading}</div> : <DataTable columns={[{ key: 'admissionNumber', label: 'Admission number' }, { key: 'fullName', label: 'Full name' }, { key: 'className', label: 'Class' }, { key: 'parentEmail', label: 'Parent email' }, { key: 'status', label: 'Status' }]} rows={visible} emptyLabel={t.noData} />}</div>;
}
