import { useEffect, useState } from 'react';
import { ArrowLeft, Check, Download, Eye, Search, X } from 'lucide-react';
import DataTable from './DataTable';
import api from '../lib/api';

export default function AdmissionsReviewModule({ rows, loading, error, t, onBack }) {
    const [items, setItems] = useState(rows); const [filter, setFilter] = useState('all'); const [search, setSearch] = useState(''); const [selected, setSelected] = useState(null); const [comment, setComment] = useState(''); const [processing, setProcessing] = useState(false); const [actionError, setActionError] = useState('');
    useEffect(() => setItems(rows), [rows]);
    const visible = items.filter((item) => (filter === 'all' || item.status === filter) && [item.applicant_name, item.parent_email, item.desired_class].some((value) => String(value || '').toLowerCase().includes(search.toLowerCase())));
    const review = async (status) => { if (!selected) return; setProcessing(true); setActionError(''); try { await api.patch(`/applications/${selected.id}/status`, { status, comment }); setItems((current) => current.map((item) => item.id === selected.id ? { ...item, status, reviewer_comment: comment } : item)); setSelected(null); setComment(''); } catch (requestError) { setActionError(requestError.response?.data?.error || 'Unable to update this application.'); } finally { setProcessing(false); } };
    return <div className="space-y-6"><button onClick={onBack} className="flex items-center gap-2 text-xs font-bold text-cyan-700"><ArrowLeft size={16} />{t.overview}</button><section className="rounded-3xl bg-[#17333d] p-6 text-white shadow-xl sm:p-8"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-teal-200">Admissions</p><h1 className="mt-2 font-display text-2xl font-bold">Review applications</h1><p className="mt-2 text-sm text-slate-300">Review every submitted detail before approving or rejecting.</p></section><section className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search applicant, email or class" className="w-full rounded-xl border border-slate-200 py-3 pl-10 pr-3 text-xs outline-none focus:border-cyan-600" /></label><div className="flex gap-2">{['all', 'pending', 'approved', 'rejected'].map((value) => <button key={value} onClick={() => setFilter(value)} className={`rounded-xl px-3 py-2 text-xs font-bold capitalize ${filter === value ? 'bg-cyan-700 text-white' : 'bg-slate-100 text-slate-600'}`}>{value}</button>)}</div></section>{error && <div className="rounded-xl bg-amber-50 px-4 py-3 text-xs text-amber-800">{error}</div>}{loading ? <div className="rounded-2xl bg-white p-14 text-center text-xs text-slate-400">{t.loading}</div> : <DataTable columns={[{ key: 'applicant_name', label: 'Applicant' }, { key: 'parent_email', label: 'Parent email' }, { key: 'desired_class', label: 'Class' }, { key: 'status', label: 'Status', render: (item) => <StatusBadge status={item.status} /> }, { key: 'action', label: 'Action', render: (item) => <button onClick={() => { setSelected(item); setComment(item.reviewer_comment || ''); setActionError(''); }} className="flex items-center gap-1 font-bold text-cyan-700"><Eye size={15} /> View</button> }]} rows={visible} emptyLabel={t.noData} />}{selected && <ReviewModal application={selected} comment={comment} setComment={setComment} error={actionError} processing={processing} onClose={() => setSelected(null)} onReview={review} />}</div>;
}

function StatusBadge({ status }) { const classes = { approved: 'bg-blue-100 text-blue-700', rejected: 'bg-red-100 text-red-700', pending: 'bg-amber-100 text-amber-700' }; return <span className={`rounded-full px-3 py-1 text-[10px] font-bold capitalize ${classes[status] || classes.pending}`}>{status}</span>; }
function ReviewModal({ application, comment, setComment, error, processing, onClose, onReview }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-900/50 p-4"><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-slate-100 p-6"><div><h2 className="font-display text-xl font-bold text-slate-800">{application.applicant_name}</h2><p className="mt-1 text-xs text-slate-500"><StatusBadge status={application.status} /> <span className="ml-2">{application.desired_class}</span></p></div><button onClick={onClose} aria-label="Close application" className="text-slate-400"><X size={20} /></button></div><div className="grid gap-4 p-6 text-sm sm:grid-cols-2"><Detail label="Parent email" value={application.parent_email} /><Detail label="Mother" value={`${application.mother_name || '-'} · ${application.mother_phone || '-'}`} /><Detail label="Father" value={`${application.father_name || '-'} · ${application.father_phone || '-'}`} /><Detail label="Gender" value={application.gender} /><Detail label="Birthday" value={application.birthday} /><Detail label="Academic year" value={application.academic_year} /><Detail label="Province" value={application.province} /><Detail label="District" value={application.district} /><Detail label="Sector" value={application.sector} /><Detail label="Cell" value={application.cell} /><Detail label="Village" value={application.village} /><Detail label="Previous school" value={application.previous_school} /></div><div className="flex flex-wrap gap-3 px-6 pb-5">{application.applicant_photo_key && <DownloadLink href={application.applicant_photo_key} label="Download photo" />}{application.report_key && <DownloadLink href={application.report_key} label="Download report" />}</div><div className="p-6"><label className="block text-xs font-bold text-slate-600">Review comment<textarea value={comment} onChange={(event) => setComment(event.target.value)} rows="4" className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-xs outline-none focus:border-cyan-600" /></label>{error && <p className="mt-3 text-xs text-rose-600">{error}</p>}{application.status === 'pending' && <div className="mt-5 flex gap-3"><button disabled={processing} onClick={() => onReview('rejected')} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-red-600 px-4 py-3 text-xs font-bold text-white disabled:opacity-50"><X size={16} /> Reject</button><button disabled={processing} onClick={() => onReview('approved')} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-xs font-bold text-white disabled:opacity-50"><Check size={16} /> Approve</button></div>}</div></div></div>; }
function DownloadLink({ href, label }) { return <a href={href} download className="flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-xs font-bold text-cyan-700"><Download size={15} />{label}</a>; }
function Detail({ label, value }) { return <div><span className="block text-[10px] font-bold uppercase tracking-wide text-slate-400">{label}</span><span className="mt-1 block text-slate-700">{value || '-'}</span></div>; }
