import { useEffect, useState } from 'react';
import { Activity, ArrowLeft, Clock3, LogIn, LogOut, Users } from 'lucide-react';
import api from '../lib/api';

export default function AuditPage({ onBack }) {
    const [data, setData] = useState(null);
    const [error, setError] = useState('');
    const load = () => api.get('/audit').then(({ data: next }) => setData(next)).catch((requestError) => setError(requestError.response?.data?.error || 'Unable to load audit data.'));
    useEffect(() => { load(); const timer = window.setInterval(load, 30000); return () => window.clearInterval(timer); }, []);
    if (error) return <div className="space-y-4"><Back onBack={onBack} /><div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div></div>;
    if (!data) return <div className="rounded-2xl border border-slate-200 bg-white p-14 text-center text-sm text-slate-500">Loading audit...</div>;
    const online = data.people.filter((person) => Number(person.isOnline) === 1 || person.isOnline === true).length;
    const maxLogins = Math.max(...data.weekly.map((item) => Number(item.logins)), 1);
    return <div className="space-y-6"><Back onBack={onBack} /><section className="rounded-3xl bg-[#073f70] p-6 text-white shadow-xl sm:p-8"><div className="flex items-start justify-between gap-5"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-cyan-200">System audit</p><h1 className="mt-2 font-display text-2xl font-bold">Weekly activity</h1><p className="mt-2 text-sm text-blue-100">Login, logout, and active-session visibility for your permitted users.</p></div><Activity size={30} className="text-emerald-300" /></div></section><div className="grid gap-4 sm:grid-cols-3"><Metric icon={Users} label="Visible users" value={data.people.length} /><Metric icon={Activity} label="Online now" value={online} /><Metric icon={LogIn} label="Weekly logins" value={data.weekly.reduce((sum, item) => sum + Number(item.logins), 0)} /></div><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-display text-lg font-bold text-slate-800">Last 7 days</h2><span className="text-sm text-slate-500">Logins per day</span></div><div className="mt-6 flex h-48 items-end gap-3 border-b border-slate-200 px-2">{lastSevenDays(data.weekly).map((item) => <div key={item.day} className="flex min-w-0 flex-1 flex-col items-center gap-2"><span className="text-sm font-bold text-cyan-700">{item.logins}</span><div className="w-full max-w-12 rounded-t-lg bg-gradient-to-t from-cyan-700 to-emerald-400" style={{ height: `${Math.max((item.logins / maxLogins) * 135, item.logins ? 8 : 2)}px` }} /><span className="text-[11px] text-slate-500">{shortDay(item.day)}</span></div>)}</div></section><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-display text-lg font-bold text-slate-800">People activity</h2></div><div className="divide-y divide-slate-100">{data.people.map((person) => <div key={person.userId} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold text-slate-800">{person.fullName}</p><p className="mt-1 text-sm capitalize text-slate-500">{person.role}</p></div><div className="grid grid-cols-3 gap-4 text-sm sm:text-right"><AuditValue label="Status" value={<span className={person.isOnline ? 'font-bold text-emerald-700' : 'text-slate-500'}>{person.isOnline ? 'Online' : 'Offline'}</span>} /><AuditValue label="Last login" value={formatDate(person.lastLoginAt)} /><AuditValue label="Last logout" value={formatDate(person.lastLogoutAt)} /></div></div>)}</div></section></div>;
}

function lastSevenDays(weekly) { const byDay = Object.fromEntries(weekly.map((item) => [String(item.day).slice(0, 10), item])); return Array.from({ length: 7 }, (_, index) => { const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - (6 - index)); const day = date.toISOString().slice(0, 10); return { day, logins: Number(byDay[day]?.logins || 0) }; }); }
function shortDay(value) { return new Date(`${value}T00:00:00`).toLocaleDateString(undefined, { weekday: 'short' }); }
function formatDate(value) { return value ? new Date(value).toLocaleString() : 'Not recorded'; }
function Back({ onBack }) { return <button onClick={onBack} className="flex items-center gap-2 text-sm font-bold text-cyan-700"><ArrowLeft size={16} /> Back to settings</button>; }
function Metric({ icon: Icon, label, value }) { return <div className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><span className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-50 text-cyan-700"><Icon size={18} /></span><div><p className="text-sm text-slate-500">{label}</p><p className="text-2xl font-black text-slate-800">{value}</p></div></div>; }
function AuditValue({ label, value }) { return <div><p className="text-[11px] font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-sm text-slate-600">{value}</p></div>; }
