CREATE TABLE IF NOT EXISTS inventory_transactions (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  item_id INT UNSIGNED NOT NULL,
  type ENUM('in','out') NOT NULL,
  quantity INT UNSIGNED NOT NULL,
  note VARCHAR(255) NULL,
  moved_by INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (item_id) REFERENCES inventory_items(id) ON DELETE CASCADE,
  FOREIGN KEY (moved_by) REFERENCES users(id)
);
