import { useEffect, useState } from 'react';
import { CalendarDays, CircleDollarSign, Users } from 'lucide-react';
import api from '../lib/api';

export default function ParentDashboardPage({ onNavigate }) {
  const [children, setChildren] = useState([]); const [messages, setMessages] = useState([]); const [error, setError] = useState('');
  useEffect(() => { Promise.all([api.get('/parent/summary'), api.get('/school-messages')]).then(([summary, communication]) => { setChildren(summary.data.children || []); setMessages(communication.data.messages || []); }).catch((requestError) => setError(requestError.response?.data?.error || 'Unable to load parent dashboard.')); }, []);
  const paid = children.reduce((sum, child) => sum + Number(child.feesPaid || 0), 0); const absences = children.reduce((sum, child) => sum + Number(child.absences || 0), 0);
  const latestMeeting = messages.find((message) => message.messageType === 'meeting');
  return <div className="space-y-6 p-5 sm:p-8"><section className="rounded-3xl bg-[#17333d] p-6 text-white shadow-xl sm:p-8"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-teal-200">Parent portal</p><h1 className="mt-3 font-display text-2xl font-bold sm:text-3xl">Your family dashboard</h1><p className="mt-3 text-sm text-slate-300">Follow your children&apos;s school progress, attendance, and payments.</p></section>{error && <p className="rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</p>}<div className="grid gap-4 sm:grid-cols-3"><Metric icon={<Users size={18} />} label="Children" value={children.length} /><Metric icon={<CircleDollarSign size={18} />} label="Paid fees" value={paid} /><Metric icon={<CalendarDays size={18} />} label="Absences" value={absences} /></div><section className="rounded-2xl border border-amber-200 bg-amber-50 p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-wide text-amber-700">Latest meeting</p><h2 className="mt-1 font-display text-lg font-bold text-slate-800">{latestMeeting?.title || 'No meeting yet'}</h2></div><button onClick={() => onNavigate('notices')} className="text-xs font-bold text-amber-800">Open communications</button></div>{latestMeeting && <p className="mt-3 text-sm text-slate-600">{latestMeeting.presentAt ? 'You attended this meeting.' : latestMeeting.viewedAt ? 'You viewed this meeting invitation but have not marked attendance.' : 'You have not viewed this meeting invitation yet.'}</p>}</section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-display text-lg font-bold">Linked students</h2><button onClick={() => onNavigate('notices')} className="text-xs font-bold text-cyan-700">School notifications</button></div><div className="mt-4 grid gap-3 md:grid-cols-2">{children.map((child) => <article key={child.id} className="rounded-xl border border-slate-200 p-4"><p className="font-bold text-slate-800">{child.fullName}</p><p className="mt-1 text-xs text-slate-500">{child.admissionNumber} · {child.className}</p><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><span className="rounded-lg bg-emerald-50 p-2 text-emerald-700">Paid: {child.feesPaid || 0}</span><span className="rounded-lg bg-amber-50 p-2 text-amber-700">Absences: {child.absences || 0}</span></div></article>)}{!children.length && <p className="text-sm text-slate-500">No linked student was found.</p>}</div></section></div>;
}
function Metric({ icon, label, value }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2 text-cyan-700">{icon}<span className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</span></div><p className="mt-3 text-2xl font-black text-slate-800">{value}</p></div>; }
