export const translations = {
  en: {
    app: 'Forever King Academy', subtitle: 'Academy management system', overview: 'Overview', students: 'Students', admissions: 'Admissions', academics: 'Academics', attendance: 'Attendance', finance: 'Finance', library: 'Library', transport: 'Transport', inventory: 'Inventory', news: 'News & events', notices: 'School notices', documents: 'Documents', settings: 'Settings', aiEngine: 'View AI Engine', goodMorning: 'Good morning', schoolPulse: 'Here is your school pulse for today.', scanId: 'Scan student ID', totalStudents: 'Total students', teachers: 'Teachers', feesCollected: 'Fees collected', pendingAdmissions: 'Pending admissions', attendanceToday: 'Attendance today', recentActivity: 'Recent activity', quickActions: 'Quick actions', viewAll: 'View all', signIn: 'Sign in', identifier: 'Username or email', email: 'Email address', password: 'Password', continue: 'Continue', verifyOtp: 'Verify OTP', otpHint: 'Enter the 6-digit code sent to your email or phone.', verify: 'Verify and continue', resend: 'Resend code', language: 'Language', logout: 'Log out', role: 'Role', active: 'Active', pending: 'Pending', present: 'Present', search: 'Search anything...', noData: 'No records to display.', loading: 'Loading...', dashboard: 'Dashboard', welcomeBack: 'Welcome back', secureAccess: 'Secure access to your school workspace.', incorrectOtp: 'Enter a valid 6-digit code.', schoolOperational: 'All systems operational', reviewApplications: 'Review applications', recordPayment: 'Record payment', createNotice: 'Create notice', timetable: 'Timetable', reports: 'Reports', notifications: 'Notifications', parentPortal: 'Parent portal', teacherPortal: 'Teacher portal', accountantPortal: 'Finance workspace', librarianPortal: 'Library workspace', dosPortal: 'Administration workspace', adminPortal: 'Full administration', footer: 'FKAMS · School operations, beautifully simple.',
  },
  rw: {
    app: 'Forever King Academy', subtitle: 'Sisitemu icunga ishuri', overview: 'Incamake', students: 'Abanyeshuri', admissions: 'Abasaba kwiga', academics: 'Amasomo', attendance: 'Abitabiriye', finance: 'Imari', library: 'Isomero', transport: 'Ubwikorezi', inventory: 'Ububiko', notices: 'Amatangazo', documents: 'Inyandiko', settings: 'Igenamiterere', aiEngine: 'Reba AI Engine', goodMorning: 'Mwaramutse', schoolPulse: 'Dore uko ishuri rihagaze uyu munsi.', scanId: 'Sikana ID y’umunyeshuri', totalStudents: 'Abanyeshuri bose', teachers: 'Abarimu', feesCollected: 'Amafaranga yakiriwe', pendingAdmissions: 'Abasaba batarasubizwa', attendanceToday: 'Abitabiriye uyu munsi', recentActivity: 'Ibikorwa bya vuba', quickActions: 'Ibikorwa byihuse', viewAll: 'Reba byose', signIn: 'Injira', identifier: 'Username cyangwa imeyili', email: 'Imeyili', password: 'Ijambo ry’ibanga', continue: 'Komeza', verifyOtp: 'Emeza OTP', otpHint: 'Andika imibare 6 yoherejwe kuri email cyangwa telefone.', verify: 'Emeza ukomeze', resend: 'Ongera wohereze', language: 'Ururimi', logout: 'Sohoka', role: 'Uruhare', active: 'Arakora', pending: 'Birategereje', present: 'Yitabiriye', search: 'Shakisha...', noData: 'Nta makuru ahari.', loading: 'Birapakirwa...', dashboard: 'Dashboard', welcomeBack: 'Murakaza neza', secureAccess: 'Injira muri workspace y’ishuri yawe mu mutekano.', incorrectOtp: 'Andika OTP y’imibare 6.', schoolOperational: 'Sisitemu yose iri gukora', reviewApplications: 'Suzuma abasaba', recordPayment: 'Andika ubwishyu', createNotice: 'Kora itangazo', timetable: 'Gahunda y’amasomo', reports: 'Raporo', notifications: 'Imenyesha', parentPortal: 'Parent portal', teacherPortal: 'Teacher portal', accountantPortal: 'Finance workspace', librarianPortal: 'Library workspace', dosPortal: 'Administration workspace', adminPortal: 'Full administration', footer: 'FKAMS · Gucunga ishuri mu buryo bworoshye.',
  },
  fr: {
    app: 'Forever King Academy', subtitle: 'Système de gestion scolaire', overview: 'Vue d’ensemble', students: 'Élèves', admissions: 'Admissions', academics: 'Académique', attendance: 'Présence', finance: 'Finances', library: 'Bibliothèque', transport: 'Transport', inventory: 'Stock', notices: 'Annonces', documents: 'Documents', settings: 'Paramètres', aiEngine: 'Voir AI Engine', goodMorning: 'Bonjour', schoolPulse: 'Voici la situation de votre école aujourd’hui.', scanId: 'Scanner ID élève', totalStudents: 'Total des élèves', teachers: 'Enseignants', feesCollected: 'Frais collectés', pendingAdmissions: 'Admissions en attente', attendanceToday: 'Présence aujourd’hui', recentActivity: 'Activité récente', quickActions: 'Actions rapides', viewAll: 'Voir tout', signIn: 'Se connecter', identifier: 'Nom d’utilisateur ou e-mail', email: 'Adresse e-mail', password: 'Mot de passe', continue: 'Continuer', verifyOtp: 'Vérifier OTP', otpHint: 'Saisissez le code à 6 chiffres envoyé par e-mail ou téléphone.', verify: 'Vérifier et continuer', resend: 'Renvoyer le code', language: 'Langue', logout: 'Déconnexion', role: 'Rôle', active: 'Actif', pending: 'En attente', present: 'Présent', search: 'Rechercher...', noData: 'Aucun résultat.', loading: 'Chargement...', dashboard: 'Tableau de bord', welcomeBack: 'Bienvenue', secureAccess: 'Accédez à votre espace scolaire en toute sécurité.', incorrectOtp: 'Saisissez un code valide à 6 chiffres.', schoolOperational: 'Tous les systèmes sont opérationnels', reviewApplications: 'Examiner les admissions', recordPayment: 'Enregistrer un paiement', createNotice: 'Créer une annonce', timetable: 'Emploi du temps', reports: 'Rapports', notifications: 'Notifications', parentPortal: 'Portail parent', teacherPortal: 'Espace enseignant', accountantPortal: 'Espace finances', librarianPortal: 'Espace bibliothèque', dosPortal: 'Espace administration', adminPortal: 'Administration complète', footer: 'FKAMS · La gestion scolaire, simplement.',
  },
};

export function getLanguage() {
  return localStorage.getItem('fkams_language') || 'en';
}
