import ClientFooter from './ClientFooter';
import ClientNavbar from './ClientNavbar';
import PublicApplicationForm from './PublicApplicationForm';
import { useState } from 'react';
import { CalendarDays } from 'lucide-react';

export default function AdmissionsPage({ language, onLanguageChange, onLogin, onNavigate, t }) {
    const [showApplication, setShowApplication] = useState(false);
    return <div className="min-h-screen bg-[#f7faf9] text-slate-800"><ClientNavbar language={language} onLanguageChange={onLanguageChange} onLogin={onLogin} onNavigate={onNavigate} t={t} /><main className="pt-[72px]"><section className="bg-[#17333d] px-5 py-20 text-white sm:px-8 lg:py-28"><div className="mx-auto max-w-5xl"><p className="text-xs font-bold uppercase tracking-[0.22em] text-teal-200">Admissions</p><h1 className="mt-5 max-w-3xl font-display text-4xl font-bold leading-tight sm:text-6xl">Your child’s next chapter starts here.</h1><p className="mt-6 max-w-2xl text-sm leading-8 text-slate-300 sm:text-base">Apply online and our admissions team will respond with the next steps for your family.</p></div></section><section className="mx-auto max-w-5xl px-5 py-16 sm:px-8 lg:py-24"><div className="mb-8 grid gap-5 md:grid-cols-3"><article className="rounded-2xl border-2 border-cyan-200 bg-white p-6 shadow-sm"><span className="grid h-11 w-11 place-items-center rounded-xl bg-cyan-50 text-cyan-700"><CalendarDays size={21} /></span><h2 className="mt-7 font-display text-lg font-bold">1. Apply</h2><p className="mt-3 text-xs leading-6 text-slate-500">Start your application when you are ready.</p><button onClick={() => setShowApplication(true)} className="mt-6 flex items-center gap-2 rounded-xl bg-cyan-700 px-4 py-3 text-xs font-bold text-white hover:bg-cyan-800">Apply now</button></article><article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><span className="grid h-11 w-11 place-items-center rounded-xl bg-cyan-50 text-cyan-700"><CalendarDays size={21} /></span><h2 className="mt-7 font-display text-lg font-bold">2. Review</h2><p className="mt-3 text-xs leading-6 text-slate-500">The admissions team reviews your application.</p></article><article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><span className="grid h-11 w-11 place-items-center rounded-xl bg-cyan-50 text-slate-700"><CalendarDays size={21} /></span><h2 className="mt-7 font-display text-lg font-bold">3. Join us</h2><p className="mt-3 text-xs leading-6 text-slate-500">Approved learners receive their next steps.</p></article></div>{showApplication && <PublicApplicationForm onClose={() => setShowApplication(false)} />}</section></main><ClientFooter onLogin={onLogin} onNavigate={onNavigate} /></div>;
}
