import { ArrowRight, BookOpen, CalendarDays, CheckCircle2, Code2, FileText, HeartHandshake, Lightbulb, Mail, MapPin, Newspaper, Users } from 'lucide-react';
import ClientNavbar from './ClientNavbar';
import ClientFooter from './ClientFooter';

const content = {
  about: { eyebrow: 'About Forever King Academy', title: 'A joyful foundation for lifelong learning.', text: 'Forever King Academy is a modern nursery and primary school in Rwanda. We combine strong academics with moral values and practical life skills to help every learner become confident and capable.', icon: HeartHandshake, cards: [['Our mission', 'To nurture confident, kind and capable young learners.'], ['Our values', 'Respect, curiosity, responsibility and service guide everyday school life.'], ['Our community', 'Families and teachers work together around every child.']] },
  academics: { eyebrow: 'Academics', title: 'Learning that meets children where they are.', text: 'Our structured nursery and primary programs build strong foundations while encouraging creativity, discovery and practical problem-solving.', icon: BookOpen, cards: [['Nursery education', 'Language, play, confidence and social development.'], ['Primary education', 'A strong academic foundation with attentive teaching.'], ['Holistic development', 'Morals, citizenship and practical skills woven into learning.']] },
  news: { eyebrow: 'Latest updates', title: 'What is happening at Forever King Academy.', text: 'Follow school milestones, classroom moments and community stories from FK Academy.', icon: Newspaper, cards: [['Learning with purpose', 'Children building confidence through curiosity and care.'], ['A community that grows together', 'Families, teachers and learners sharing progress.'], ['Skills for tomorrow', 'Practical learning experiences for a changing world.']] },
  innovations: { eyebrow: 'Innovation', title: 'Small ideas can shape a brighter future.', text: 'We encourage learners to observe, imagine, build and share solutions to real-world challenges.', icon: Lightbulb, cards: [['Creative projects', 'Hands-on activities that turn questions into ideas.'], ['Digital confidence', 'Age-appropriate technology and responsible exploration.'], ['Problem solving', 'Teamwork and reflection help learners find better answers.']] },
  publications: { eyebrow: 'Publications', title: 'Stories and resources from our school community.', text: 'Explore public school updates, learning resources and community highlights.', icon: FileText, cards: [['School updates', 'Important news and announcements for families.'], ['Learning resources', 'Helpful guidance for supporting children at home.'], ['Community stories', 'Celebrating the people who make our school special.']] },
  campus: { eyebrow: 'Campus life', title: 'A safe place to learn, play and belong.', text: 'Everyday school life balances focused learning with friendship, movement, creativity and care.', icon: Users, cards: [['Clubs and activities', 'Discover interests beyond the classroom.'], ['Wellbeing', 'A caring environment where children feel seen.'], ['Family connection', 'Regular communication keeps home and school close.']] },
  admissions: { eyebrow: 'Admissions', title: 'Your child’s next chapter starts here.', text: 'Apply online and our admissions team will respond with the next steps for your family.', icon: CalendarDays, cards: [['1. Apply', 'Share your child and family information online.'], ['2. Review', 'The admissions team reviews your application.'], ['3. Join us', 'Approved learners receive their next steps.']] },
  contact: { eyebrow: 'Contact us', title: 'We would love to hear from your family.', text: 'Reach out for admissions, school information or a conversation about your child’s learning.', icon: Mail, cards: [['Phone', '+250 788 390 989'], ['Email', 'foreverkingacademy@gmail.com'], ['Location', 'Murambi, Rwanda']] },
};

export default function ClientContentPage({ page, language, onLanguageChange, onLogin, onNavigate, t }) {
  const item = content[page] || content.about; const Icon = item.icon;
  return <div className="min-h-screen bg-[#f7faf9] text-slate-800"><ClientNavbar language={language} onLanguageChange={onLanguageChange} onLogin={onLogin} onNavigate={onNavigate} t={t} /><main className="pt-[72px]"><section className="relative overflow-hidden bg-[#17333d] px-5 py-24 text-white sm:px-8 lg:py-32"><div className="absolute -right-20 -top-28 h-80 w-80 rounded-full bg-teal-300/10 blur-3xl" /><div className="relative mx-auto max-w-5xl"><p className="text-xs font-bold uppercase tracking-[0.22em] text-teal-200">{item.eyebrow}</p><h1 className="mt-5 max-w-3xl font-display text-4xl font-bold leading-tight sm:text-6xl">{item.title}</h1><p className="mt-6 max-w-2xl text-sm leading-8 text-slate-300 sm:text-base">{item.text}</p></div></section><section className="mx-auto max-w-5xl px-5 py-16 sm:px-8 lg:py-24"><div className="grid gap-5 md:grid-cols-3">{item.cards.map(([title, text]) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><span className="grid h-11 w-11 place-items-center rounded-xl bg-cyan-50 text-cyan-700"><Icon size={21} /></span><h2 className="mt-7 font-display text-lg font-bold">{title}</h2><p className="mt-3 text-xs leading-6 text-slate-500">{text}</p></article>)}</div><div className="mt-12 rounded-2xl bg-[#eaf5f3] p-6 sm:p-8"><div className="flex items-start gap-4"><CheckCircle2 className="mt-1 shrink-0 text-teal-600" size={21} /><div><h2 className="font-display text-lg font-bold">Forever King Digital Platform</h2><p className="mt-2 text-sm leading-7 text-slate-600">School information, admissions and family services are connected in one secure platform.</p><button onClick={() => onNavigate('home')} className="mt-5 flex items-center gap-2 text-xs font-bold text-cyan-700">Back to home <ArrowRight size={15} /></button></div></div></div></section></main><ClientFooter onLogin={onLogin} onNavigate={onNavigate} /></div>;
}
