import { useEffect, useState } from 'react';
import { ArrowLeft, CalendarDays, Check, CheckCircle2 } from 'lucide-react';
import api from '../lib/api';
import AttendanceStartPage from './attendance/AttendanceStartPage';
import AttendanceSetupPage from './attendance/AttendanceSetupPage';
import AttendanceRosterPage from './attendance/AttendanceRosterPage';
import AttendanceReportPage from './attendance/AttendanceReportPage';

const steps = ['Open Attendance', 'Choose class and date', 'Student list', 'Attendance report'];

export default function AttendancePage({ user, t, onBack }) {
    if (!['admin', 'dos', 'teacher'].includes(user?.role)) return <ReadOnlyAttendance user={user} t={t} onBack={onBack} />;
    return <MarkAttendance t={t} onBack={onBack} />;
}

function MarkAttendance({ t, onBack }) {
    const [step, setStep] = useState(1); const [classes, setClasses] = useState([]); const [students, setStudents] = useState([]); const [classId, setClassId] = useState(''); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [statuses, setStatuses] = useState({}); const [comments, setComments] = useState({}); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
    useEffect(() => { api.get('/classes?current=true').then(({ data }) => setClasses(data.classes || [])).catch((e) => setError(e.response?.data?.error || 'Unable to load classes.')); }, []);
    const selectedClass = classes.find((item) => String(item.id) === classId);
    const loadStudents = async () => { if (!classId || !date) return setError('Select a class and date first.'); setError(''); try { const { data } = await api.get('/students'); const next = (data.students || []).filter((student) => student.className === selectedClass?.name && student.status === 'active'); setStudents(next); setStatuses(Object.fromEntries(next.map((student) => [student.id, 'present']))); setComments({}); setStep(3); } catch (e) { setError(e.response?.data?.error || 'Unable to load students.'); } };
    const save = async () => { const excusedMissing = students.some((student) => statuses[student.id] === 'excused' && !comments[student.id]?.trim()); if (excusedMissing) return setError('Add a comment for every excused student.'); setSaving(true); setError(''); try { await Promise.all(students.map((student) => api.post('/attendance', { studentId: student.id, status: statuses[student.id], comment: comments[student.id] || '', date }))); setNotice('Attendance saved successfully.'); setStep(4); } catch (e) { setError(e.response?.data?.error || 'Unable to save attendance.'); } finally { setSaving(false); } };
    return <div className="space-y-6"><button onClick={onBack} className="flex items-center gap-2 text-xs font-bold text-cyan-700"><ArrowLeft size={15} />{t.overview}</button><header className="rounded-3xl bg-[#17333d] p-6 text-white shadow-xl sm:p-8"><div className="flex items-center gap-4"><CalendarDays className="text-teal-300" size={30} /><div><p className="text-[10px] uppercase tracking-wider text-teal-200">School attendance system</p><h1 className="mt-2 font-display text-2xl font-bold">Take Attendance</h1></div></div></header>{error && <Notice tone="error">{error}</Notice>}{notice && <Notice><CheckCircle2 size={16} />{notice}</Notice>}<div className="grid gap-3 sm:grid-cols-4">{steps.map((label, index) => <div key={label} className={`rounded-2xl border p-4 ${step === index + 1 ? 'border-cyan-400 bg-cyan-50' : step > index + 1 ? 'border-emerald-300 bg-emerald-50' : 'border-slate-200 bg-white'}`}><span className="grid h-8 w-8 place-items-center rounded-full bg-cyan-800 text-sm font-bold text-white">{step > index + 1 ? <Check size={16} /> : index + 1}</span><p className="mt-3 text-xs font-bold text-slate-700">{label}</p></div>)}</div>{step === 1 && <AttendanceStartPage onNext={() => setStep(2)} />}{step === 2 && <AttendanceSetupPage classes={classes} classId={classId} date={date} setClassId={setClassId} setDate={setDate} onBack={() => setStep(1)} onNext={loadStudents} />}{step === 3 && <AttendanceRosterPage students={students} statuses={statuses} setStatus={(id, value) => setStatuses((current) => ({ ...current, [id]: value }))} className={selectedClass?.name} date={date} onBack={() => setStep(2)} onNext={() => setStep(4)} />}{step === 4 && <AttendanceReportPage students={students} statuses={statuses} comments={comments} setComment={(id, value) => setComments((current) => ({ ...current, [id]: value }))} className={selectedClass?.name} date={date} saving={saving} onBack={() => setStep(3)} onSave={save} />}</div>;
}

function ReadOnlyAttendance({ user, t, onBack }) { const [records, setRecords] = useState([]); const [error, setError] = useState(''); useEffect(() => { const load = async () => { try { const response = user.role === 'student' ? await api.get('/student/profile') : await api.get('/parent/summary'); const id = user.role === 'student' ? response.data.profile?.id : response.data.children?.[0]?.id; if (id) setRecords((await api.get(`/attendance?studentId=${id}`)).data.attendance || []); } catch (e) { setError(e.response?.data?.error || 'Unable to load attendance.'); } }; load(); }, [user]); return <div className="space-y-6"><button onClick={onBack} className="flex items-center gap-2 text-xs font-bold text-cyan-700"><ArrowLeft size={15} />{t.overview}</button><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h1 className="font-display text-2xl font-bold text-slate-800">My Attendance</h1>{error ? <p className="mt-4 text-xs text-rose-600">{error}</p> : records.map((record) => <div key={`${record.date}-${record.status}`} className="flex justify-between border-b border-slate-100 py-3 text-sm"><span>{String(record.date).slice(0, 10)}</span><b className="capitalize text-cyan-700">{record.status}</b></div>)}</section></div>; }
function Notice({ children, tone = 'success' }) { return <div className={`flex items-center gap-2 rounded-xl border px-4 py-3 text-xs ${tone === 'error' ? 'border-rose-200 bg-rose-50 text-rose-700' : 'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{children}</div>; }